/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Pedro França (https://sketchfab.com/pedrofbfranca)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/all-star-converse-f3428b2583a0415c99b3b08feee48d79
title: All Star Converse
*/

import {useRef} from 'react'

import {useGLTF} from '@react-three/drei'
import * as THREE from 'three'
import {GLTF} from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
    defaultMaterial_4: THREE.Mesh
    defaultMaterial_5: THREE.Mesh
    defaultMaterial_6: THREE.Mesh
    defaultMaterial_7: THREE.Mesh
    defaultMaterial_8: THREE.Mesh
    defaultMaterial_9: THREE.Mesh
    defaultMaterial_10: THREE.Mesh
    defaultMaterial_11: THREE.Mesh
    defaultMaterial_12: THREE.Mesh
    defaultMaterial_13: THREE.Mesh
    defaultMaterial_14: THREE.Mesh
    defaultMaterial_15: THREE.Mesh
    defaultMaterial_16: THREE.Mesh
    defaultMaterial_17: THREE.Mesh
    defaultMaterial_18: THREE.Mesh
  }
  materials: {
    Ponta: THREE.MeshStandardMaterial
    Detalhe_Cadar__o: THREE.MeshStandardMaterial
    Costuras: THREE.MeshStandardMaterial
    Tag_Traseira: THREE.MeshStandardMaterial
    Tag_Tecido: THREE.MeshStandardMaterial
    Tag_Lingua: THREE.MeshStandardMaterial
    Metais: THREE.MeshStandardMaterial
    Cadar__o: THREE.MeshStandardMaterial
    Palmilha: THREE.MeshStandardMaterial
    Solado_Frente: THREE.MeshStandardMaterial
    Borracha_Lateral: THREE.MeshStandardMaterial
    Detalhe_Borracha_Lateral: THREE.MeshStandardMaterial
    Lingua: THREE.MeshStandardMaterial
    Tecido_001: THREE.MeshStandardMaterial
  }
}

export default function Model(
  props: JSX.IntrinsicElements['group']
): JSX.Element {
  const group = useRef<THREE.Group>()
  const {nodes, materials} = useGLTF('/all_star/scene.gltf') as GLTFResult

  return (
    <group ref={group} rotation={[0.5, 2.4, 0]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            material={materials.Ponta}
            geometry={nodes.defaultMaterial.geometry}
          />
          <mesh
            material={materials.Detalhe_Cadar__o}
            geometry={nodes.defaultMaterial_1.geometry}
          />
          <mesh
            material={materials.Costuras}
            geometry={nodes.defaultMaterial_2.geometry}
          />
          <mesh
            material={materials.Costuras}
            geometry={nodes.defaultMaterial_3.geometry}
          />
          <mesh
            material={materials.Costuras}
            geometry={nodes.defaultMaterial_4.geometry}
          />
          <mesh
            material={materials.Tag_Traseira}
            geometry={nodes.defaultMaterial_5.geometry}
          />
          <mesh
            material={materials.Tag_Tecido}
            geometry={nodes.defaultMaterial_6.geometry}
          />
          <mesh
            material={materials.Tag_Lingua}
            geometry={nodes.defaultMaterial_7.geometry}
          />
          <mesh
            material={materials.Metais}
            geometry={nodes.defaultMaterial_8.geometry}
          />
          <mesh
            material={materials.Cadar__o}
            geometry={nodes.defaultMaterial_9.geometry}
          />
          <mesh
            material={materials.Cadar__o}
            geometry={nodes.defaultMaterial_10.geometry}
          />
          <mesh
            material={materials.Palmilha}
            geometry={nodes.defaultMaterial_11.geometry}
          />
          <mesh
            material={materials.Solado_Frente}
            geometry={nodes.defaultMaterial_12.geometry}
          />
          <mesh
            material={materials.Borracha_Lateral}
            geometry={nodes.defaultMaterial_13.geometry}
          />
          <mesh
            material={materials.Detalhe_Borracha_Lateral}
            geometry={nodes.defaultMaterial_14.geometry}
          />
          <mesh
            material={materials.Lingua}
            geometry={nodes.defaultMaterial_15.geometry}
          />
          <mesh
            material={materials.Tecido_001}
            geometry={nodes.defaultMaterial_16.geometry}
          />
          <mesh
            material={materials.Tecido_001}
            geometry={nodes.defaultMaterial_17.geometry}
          />
          <mesh
            material={materials.Tecido_001}
            geometry={nodes.defaultMaterial_18.geometry}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/all_star/scene.gltf')
