/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Stéphane Agullo (https://sketchfab.com/sa3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/5ce4b1465c83432d9bb7e3c30232c02b
title: EARTH
*/

import * as THREE from 'three'
import React, {useRef, useState, useEffect} from 'react'
import {useFrame, useLoader} from 'react-three-fiber'
import {useGLTF} from '@react-three/drei'

import {useAnimations} from '@react-three/drei'
import {GLTFLoader, GLTF} from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    EARTHLayer1_TERRE_0: THREE.Mesh
    EARTHLayer2_NUAGES_0: THREE.Mesh
    EARTHLayer3_01_0: THREE.Mesh
    EARTHLayer4_02_0: THREE.Mesh
    EARTHLayer5_03_0: THREE.Mesh
    EARTHLayer6_04_0: THREE.Mesh
    EARTHLayer7_05_0: THREE.Mesh
    EARTHLayer8_06_0: THREE.Mesh
  }
  materials: {
    TERRE: THREE.MeshStandardMaterial
    NUAGES: THREE.MeshStandardMaterial
    material_3: THREE.MeshStandardMaterial
    material_4: THREE.MeshStandardMaterial
    material_5: THREE.MeshStandardMaterial
    material_6: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    material_8: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Base Stack'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const gltf = useLoader(GLTFLoader, '/scene.gltf') as GLTFResult
  // const {actions} = useAnimations(animations, group)
  return (
    <primitive
      castShadow
      ref={group}
      object={gltf}
      scale={[0.1, 0.1, 0.1]}
      position={[5, -3, 0]}
    />
  )
}

// useGLTF.preload('/scene.gltf')
